.TH fiss 8
.SH NAME
fiss \- a UNIX process no 1
.SH SYNOPSIS
.TP
\fBfsvc\fR
when running as PID 0 (as init)
.TP
\fBfsvc\fR <0|6>
when running regulary to controll init
.SH CONTROLLING
If \fBfinit\fR is invoked by any other user than \fIfroot\fR, it failes.
.P
.TP
\fBfinit\fR 0
halts the system
.TP
\fBfinit\fR 6
reboots the system
.SH DESCRIPTION
\fBfiss\fR must be run as Unix process no 1 if invoked without arguments and
handles the boot process in user-land.
This happens in three stages:
.SH STAGE 1
\fBfiss\fR runs \fI/etc/fiss/start\fR and waits for it to terminate.
The system's one time tasks are done here.
\fI/etc/fiss/start\fR has full control of \fI/dev/console\fR to be able
to start an emergency shell if the one time initialization tasks fail. If \fI/etc/fiss/start\fR
crashes,\fBfinit\fR will skip stage 2 and enter stage 3.
.SH STAGE 2
\fBfiss\fR starts all services in \fI/etc/fiss/service.d\fR which should not return until system shutdown; if it crashes,
it will be restarted.
.SH STAGE 3
If \fBfiss\fR
is told to shutdown the system, it terminates stage 2 if it is running, and runs
\fI/etc/fiss/stop\fR.
The systems tasks to shutdown and possibly halt or reboot the system are
done here.
If stage 3 returns, \fBfinit\fR checks if the file
.SH SIGNALS
\fBfinit\fR only accepts signals in stage 2.
.P
If \fBfinit\fR receives a CONT signal and the file \fBfinit\fR
is told to shutdown the system.
.P
if \fBfinit\fR receives an INT signal, \fBfinit\fR restarts the system.
.SH SEE ALSO
fiss-init(8),
runsvdir(8),
runsvchdir(8),
sv(8),
runsv(8),
chpst(8),
utmpset(8),
svlogd(8)
.SH AUTHOR
Friedel Schön <derfriedmundschoen@gmail.com>