." Manpage for fsvc.
.TH fsvc 1 "2023-04-13" "1.0" "fsvc man page"
.SH NAME
fsvc - fiss' service controller
.SH SYNOPSIS
\fBfsvc\fR start [--pin] <service>

\fBfsvc\fR stop [--pin] <service>

\fBfsvc\fR enable [--once] <service>

\fBfsvc\fR disable [--once] <service>

\fBfsvc\fR kill <service> <signal|signo>

\fBfsvc\fR status [--check] [<service>]

\fBfsvc\fR pause <service>

\fBfsvc\fR resume <service>

\fBfsvc\fR switch [--reset] <runlevel>
.SH DESCRIPTION
\fBfsvc\fR is a command line tool for controlling services on a FISS system. It provides various commands for starting, stopping, enabling, disabling, sending signals to, checking the status of, pausing, resuming, and switching the runlevel of services.
.SH OPTIONS
The following options are available:
.TP
\fB--pin\fR
Pins the state. If issued with \fBstart\fR it will cause the service to restart, otherwise if will cause the service to be hold down.
.TP
\fB--once\fR
Specifies that the service should only be enabled/disabled once and not automatically started/stopped on subsequent bootups.
.TP
\fB--check\fR
Command will return 0 if the specified service is active otherwise 1
.TP
\fB--reset\fR
Specifies that the switch command should reset all running services (if manually set to up/down)
.SH COMMANDS
The following commands are available:
.TP
\fBstart\fR
Starts the specified service. A synonym is \fBup\fR.
.TP
\fBstop\fR
Stops the specified service. A synonym is \fBdown\fR.
.TP
\fBenable\fR
Enables the specified service, causing it to automatically start on subsequent bootups.
.TP
\fBdisable\fR
Disables the specified service, causing it to not start automatically on subsequent bootups.
.TP
\fBkill\fR
Sends the specified signal or signal number to the specified service. A synonym is \fBsend\fR.
.TP
\fBstatus\fR
Displays the status of the specified service. If no service is specified, displays the status of all services.
.TP
\fBpause\fR
Pauses the specified service.
.TP
\fBresume\fR
Resumes the specified service.
.TP
\fBswitch\fR
Switches the runlevel to the specified value.
.SH SEE ALSO
finit(1),
fsvc(8),
fsvs(8),
halt(8),
modules-load(8),
shutdown(8) 
.SH AUTHOR
Friedel Schön <derfriedmundschoen@gmail.com>