.TH halt 8 "MAY 2023" "0.1.0" "fiss man page"
.SH NAME
.PP
halt, reboot, poweroff \- stop the system
.SH SYNOPSIS
.PP
\fB\fCpoweroff\fR [\fB\fC\-n\fR] [\fB\fC\-f\fR] [\fB\fC\-d\fR] [\fB\fC\-w\fR] [\fB\fC\-b\fR]
.PP
\fB\fCreboot\fR [\fB\fC\-n\fR] [\fB\fC\-f\fR] [\fB\fC\-d\fR] [\fB\fC\-w\fR] [\fB\fC\-b\fR]
.PP
\fB\fChalt\fR [\fB\fC\-n\fR] [\fB\fC\-f\fR] [\fB\fC\-d\fR] [\fB\fC\-w\fR] [\fB\fC\-b\fR]
.SH DESCRIPTION
.PP
\fB\fCpoweroff\fR / \fB\fCreboot\fR / \fB\fChalt\fR tells \fB\fCinit\fR to stop running services and stop the system. Invoked without \fB\fC\-f\fR, it is a shortcut for \fB\fCinit <0|6>\fR
.SH OPTIONS
.PP
\fB\fC\-n\fR
Don't sync devices, this doensn't imply that the kernel is not synced already
.PP
\fB\fC\-f\fR
Forces halt / reboot without notifying \fB\fCinit\fR\&. Forcing the system to halt should be the last hope and can be dangerous, you should not try it
.PP
\fB\fC\-d\fR
Don't write the \fIwtmp\fP record
.PP
\fB\fCw\fR
Only write the wtmp record, no further action
.SH SEE ALSO
.PP
.BR finit (1), 
.BR fsvc (8), 
.BR fsvs (8), 
.BR halt (8), 
.BR modules-load (8), 
.BR shutdown (8),
.SH AUTHOR
.PP
Based on the version of Leah Neukirchen <\[la]leah@vuxu.org\[ra]>, rewritten by Friedel Schön <\[la]derfriedmundschoen@gmail.com\[ra]>
