#!/bin/sh
# vim: set ts=4 sw=4 et:

PATH=/usr/bin:/usr/sbin

. /usr/share/fiss/utils

msg "Welcome to Void (fiss version)!"

[ -r /etc/rc.conf ] && . /etc/rc.conf

# Start core services: one-time system tasks.
detect_virt
for f in /etc/fiss/start.d/*.sh; do
	[ -r $f ] && . $f
done

dmesg >/var/log/dmesg.log
if [ $(sysctl -n kernel.dmesg_restrict 2>/dev/null) -eq 1 ]; then
	chmod 0600 /var/log/dmesg.log
else
	chmod 0644 /var/log/dmesg.log
fi

# create files for controlling runit
mkdir -p /run/fiss/log

msg "Initialization complete, running stage 2..."

[ -x /etc/rc.local ] && /etc/rc.local