#!/bin/sh
# vim: set ts=4 sw=4 et:

PATH=/usr/bin:/usr/sbin

. /usr/share/fiss/utils

msg "Welcome to Void (fiss version)!"

[ -r /etc/rc.conf ] && . /etc/rc.conf

# Start core services: one-time system tasks.
detect_virt

for f in /etc/start.d/*.sh; do
	[ -r $f ] && . $f
done


msg "Initialization complete, running stage 2..."

[ -x /etc/rc.local ] && /etc/rc.local