name: Build

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
    
      - name: Configuring Environment
        run: ./configuring --verbose
      
      - name: Build Binaries
        run: make binary
        
      - name: Build Documentation
        run: make documentation
        
      - name: Build Manuals
        run: make manual
